In [1]:
from sklearn.pipeline import Pipeline
## feature Scaling
from sklearn.preprocessing import StandardScaler
## The machine model algorithm
from sklearn.linear_model import LogisticRegression

In [2]:
# I want to combine everything

In [3]:
steps = [("standard_scalar", StandardScaler()),
         ("classifier", LogisticRegression())]

In [4]:
steps

[('standard_scalar', StandardScaler()), ('classifier', LogisticRegression())]

In [7]:
# If i want to impute it into pipeline al you need is to give the steps
pipe = Pipeline(steps)

In [8]:
# We have techniques to visualise this pipeline variable in an efficient way

In [9]:
# Visualize Pipeline
from sklearn import set_config

In [10]:
set_config(display= "diagram")

In [11]:
pipe

Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('classifier', LogisticRegression())])

In [15]:
## Creating a dataset
from sklearn.datasets import make_classification
x, y = make_classification(n_samples = 1000)

In [18]:
x.shape

(1000, 20)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y,test_size=0.33, random_state=42)

In [21]:
X_train

array([[-0.22026978, -0.02875269,  1.08127191, ..., -0.36206128,
        -2.10268288, -0.19605741],
       [-1.17467038,  0.22754475, -0.53034529, ..., -2.15383764,
        -1.34170955, -0.81526013],
       [ 0.67226844, -0.43806515,  2.95745889, ..., -1.52937135,
        -0.816716  , -1.20521657],
       ...,
       [ 1.30564154, -0.5448647 , -1.2540053 , ...,  0.69030319,
         1.15437525, -0.01838504],
       [-1.45305817,  0.40720343,  0.76789154, ..., -1.71071848,
        -0.8199656 ,  0.1812321 ],
       [ 0.92656058,  1.52549018,  1.2838271 , ..., -1.0757164 ,
         0.39496566,  0.26099669]])

In [50]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('standard_scalar', StandardScaler()),
                ('classifier', LogisticRegression())])

In [27]:
y_pred = pipe.predict(X_test)
y_pred

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,

# Example 2
Displaying a pipeline with standard scalar, dimensionality reduction and then estimator

In [43]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [52]:
steps = [("scaling", StandardScaler()),
        ("PCA", PCA(n_components= 3)),
        ("SVC", SVC())]

In [53]:
pipe_2 = Pipeline(steps)
pipe_2

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [54]:
# You can use it to check if it is working
pipe_2['scaling'].fit_transform(X_train)

array([[-0.26740474,  0.02851847,  1.05075826, ..., -0.33886745,
        -1.61060252, -0.23739549],
       [-1.20285143,  0.2884309 , -0.52058524, ..., -2.09702052,
        -1.00531427, -0.85544334],
       [ 0.60740813, -0.38656719,  2.88006001, ..., -1.48427256,
        -0.58772746, -1.24467248],
       ...,
       [ 1.22820276, -0.4948731 , -1.22616125, ...,  0.69374904,
         0.98010458, -0.06005449],
       [-1.47571058,  0.47062359,  0.74520914, ..., -1.66221664,
        -0.59031223,  0.13919034],
       [ 0.85665015,  1.60468336,  1.24825166, ..., -1.03913059,
         0.37606015,  0.21880617]])

In [55]:
pipe_2.fit(X_train, y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

## Complex examples of column transformer

In [60]:
from sklearn.impute import SimpleImputer
import numpy as np

In [68]:
## numerical processing pipeline
numeric_processor = Pipeline(
    steps = [("imputation_mean", SimpleImputer(missing_values= np.nan, strategy= "mean")),
             ("scaler", StandardScaler()),
            ]
)

In [69]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [74]:
from sklearn.preprocessing import OneHotEncoder
## categorical processing pipeline
categorical_processor = Pipeline(
    steps = [("imputation_constant", SimpleImputer(fill_value = "missing")),
            ("Encoder", OneHotEncoder())]
)

In [75]:
categorical_processor

Pipeline(steps=[('imputation_constant', SimpleImputer(fill_value='missing')),
                ('Encoder', OneHotEncoder())])

In [77]:
# I will try to combine both the pipeline
# We will try ro import another module from sklearn

In [79]:
# Combining processing techniques
from sklearn.compose import ColumnTransformer

In [82]:
preprocessor = ColumnTransformer(
    [("categorical", categorical_processor, ["gender", "City"]),
    ("numerical", numeric_processor, ["age", "height"])]
)

In [83]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing')),
                                                 ('Encoder', OneHotEncoder())]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [84]:
from sklearn.pipeline import make_pipeline

In [86]:
# We need to create a custom pipeline
pipe = make_pipeline(preprocessor,LogisticRegression())

In [87]:
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing')),
                                                                  ('Encoder',
                                                                   OneHotEncoder())]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])